### PR TITLE
Test for 00ea30f which fixes #875

### LINKED ISSUE #875: Strange advice: testImplementation -> runtimeOnly (instead of testRuntimeOnly)
**Build scan link**

**Plugin version**
1.19.0

**Gradle version**
7.6

**(Optional) Android Gradle Plugin (AGP) version**
7.4.2

**`reason` output for bugs relating to incorrect advice**
```
> Task :stringers:reason

----------------------------------------
You asked about the dependency 'org.robolectric:robolectric:4.4'.
You have been advised to change this dependency to 'runtimeOnly' from 'testImplementation'.
----------------------------------------

There is no path from :stringers to org.robolectric:robolectric:4.4 for debugCompileClasspath


There is no path from :stringers to org.robolectric:robolectric:4.4 for debugRuntimeClasspath


Shortest path from :stringers to org.robolectric:robolectric:4.4 for debugUnitTestCompileClasspath:
:stringers
\--- org.robolectric:robolectric:4.4

Shortest path from :stringers to org.robolectric:robolectric:4.4 for debugUnitTestRuntimeClasspath:
:stringers
\--- org.robolectric:robolectric:4.4

There is no path from :stringers to org.robolectric:robolectric:4.4 for debugAndroidTestCompileClasspath


There is no path from :stringers to org.robolectric:robolectric:4.4 for debugAndroidTestRuntimeClasspath


There is no path from :stringers to org.robolectric:robolectric:4.4 for releaseCompileClasspath


There is no path from :stringers to org.robolectric:robolectric:4.4 for releaseRuntimeClasspath


Shortest path from :stringers to org.robolectric:robolectric:4.4 for releaseUnitTestCompileClasspath:
:stringers
\--- org.robolectric:robolectric:4.4

Shortest path from :stringers to org.robolectric:robolectric:4.4 for releaseUnitTestRuntimeClasspath:
:stringers
\--- org.robolectric:robolectric:4.4

Source: debug, main
-------------------
(no usages)

Source: release, main
---------------------
(no usages)

Source: debug, test
-------------------
* Provides 1 service loader: org.robolectric.plugins.DefaultSdkProvider (implies testRuntimeOnly).

Source: release, test
---------------------
* Provides 1 service loader: org.robolectric.plugins.DefaultSdkProvider (implies testRuntimeOnly).

Source: debug, android_test
---------------------------
(no usages)
```

**Describe the bug**
Robolectric is a test dependency. It's even used as
```java
import org.junit.runner.RunWith;
import org.robolectric.annotation.Config;
import org.robolectric.annotation.internal.DoNotInstrument;

@RunWith(AndroidJUnit4.class)
@Config(sdk = Build.VERSION_CODES.P)
@DoNotInstrument
public class ...Test {
```
but even if we ignore this, based on the
```
* Provides 1 service loader: org.robolectric.plugins.DefaultSdkProvider (implies testRuntimeOnly).
```
it sounds like `testRuntimeOnly` is the correct suggestion.

**To Reproduce**
```
// StandardTransformTest
    @Test fun `robolectric should be testRuntimeOnly`() {
      val id = "org.robolectric:robolectric"
      val coordinates = ModuleCoordinates(id, "4.4")
      val usages = setOf(
        usage(bucket = Bucket.RUNTIME_ONLY, variant = "test", kind = SourceSetKind.TEST),
      )
      val declarations = Declaration(id, "testImplementation").intoSet()

      val actual = StandardTransform(coordinates, declarations, supportedSourceSets).reduce(usages)

      assertThat(actual).containsExactly(
        Advice.ofChange(coordinates, "testImplementation", "testRuntimeOnly"),
      )
    }
```

**Expected behavior**
```
You have been advised to change this dependency to 'testRuntimeOnly' from 'testImplementation'.
```

**Additional context**
This is fixed by https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/00ea30f44d78f102d4260fe78367f1c1195c827c, but there was no test added for the problem, the above one could help prevent regressions.

### PR DESCRIPTION
**Pull request by TWiStErRob**
Test for 00ea30f which fixes #875

### CODE REVIEW

**Comment by autonomousapps** [comment]
Hi! Thanks for the PR and sorry for the delay. Would you mind rebasing? If it passes after that, I'll merge.

**Review by autonomousapps — APPROVED** [review]

**Comment by TWiStErRob** [comment]
I don't have PC access, can you please enable this option for the repository:

Screenshot_20230422-225321

... so it can be done from the GitHub UI with a Click/Tap?

**Comment by autonomousapps** [comment]
Done!

**Comment by TWiStErRob** [comment]
Sure, agree, it's just way easier with this button:

Screenshot_20230423-205636

**Comment by TWiStErRob** [comment]
Being able to rebase also allows for fixing on GitHub UI on mobile, so this is ready to merge after a re-review.

Rebase was clean as there were no conflicts, but it failed as you expected.

**Review by autonomousapps — APPROVED** [review]

**Pull request merged**
