### PR TITLE
Publish a snapshot on each PR.

### PR DESCRIPTION
**Pull request by autonomousapps**

### CODE REVIEW

**Comment by stephanenicolas** [comment]
It's a very good idea. But how are we gonna deal with version numbers ? Is it gonna be like `0.40-branch-SNAPSHOT` ?

**Comment by autonomousapps** [comment]
I thought I'd keep it simple, at least to start. Snapshots aren't expected
to be identical each time you retrieve them, and Gradle even treats them
special, so I thought I'd just publish with a snapshot suffix and that
would be good enough.

**Comment by stephanenicolas** [comment]
I think it would be better to do this when master builds. 
For PRs, you need to distinguish the branches.

**Comment by autonomousapps** [comment]
Even if we only published on master, we'd still have to deal with the version number issue. Branch / no branch doesn't matter. Either way, we're overwriting the snapshot over and over again. And I think this is fine, at least to start. Snapshots are volatile by nature.

**Comment by autonomousapps** [comment]
Although now that I think about it more, I think you're right we should only publish from master. Otherwise different PRs will just overwrite each other, which is weird. Thanks for pushing.

**Pull request closed without merging**
