### PR TITLE
Use buffered reading when reading files in SynthesizeDependenciesTask

### LINKED ISSUE #828: OutOfMemoryError when de-serializing the input for SynthesizeDependenciesTask
**Build scan link**
Private, can't share unfortunately.

**Plugin version**
`v1.17.0`

**Gradle version**
`7.4.2`

**(Optional) Android Gradle Plugin (AGP) version**
Not applicable.

**`reason` output for bugs relating to incorrect advice**
Not applicable.

**Describe the bug**
An `OutOfMemoryError` is sometimes thrown when de-serializing the input for `SynthesizeDependenciesTask`
```
Caused by: java.lang.OutOfMemoryError: Java heap space
at kotlin.io.TextStreamsKt.copyTo(ReadWrite.kt:125)
at kotlin.io.TextStreamsKt.copyTo$default(ReadWrite.kt:120)
at kotlin.io.TextStreamsKt.readText(ReadWrite.kt:107)
at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
at com.autonomousapps.tasks.SynthesizeDependenciesTask$SynthesizeDependenciesWorkAction.execute(SynthesizeDependenciesTask.kt:245)
```

**To Reproduce**
It's not happening deterministically unfortunately, but having an insane number of dependencies sometimes triggers this.

**Expected behavior**
No OOM exception.

**Additional context**
Similar to #823 where it was happening when serializing, the de-serializing is done without buffering.

### PR DESCRIPTION
**Pull request by daanschipper**
Fixes #828

### CODE REVIEW

**Comment by daanschipper** [comment]
@autonomousapps Could you review this one? 1% of total builds are hit by this issue:
```
Execution failed for task *
> A failure occurred while executing com.autonomousapps.tasks.SynthesizeDependenciesTask$SynthesizeDependenciesWorkAction
   > Java heap space
```

**Review by autonomousapps — APPROVED** [review]
LGTM, thanks!

**Comment by autonomousapps** [comment]
@daanschipper feel free to submit another PR with this [idea](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/829#issuecomment-1350636244).

**Comment by daanschipper** [comment]
@autonomousapps Can you release a new version with this fix again? 🙏

**Comment by TimvdLippe** [comment]
@autonomousapps apologies for another ping (I am a colleague of Daan). We are hitting this particular issue quite often and are currently contemplating temporarily disabling the plugin to unblock our engineers. Ideally we don't do that, but we are running out of options. A new release would help us a lot to get the fix in our build. Would that be a possibility today? Thank you so much for your dedication to this project and we are eager to continue contributing to it.

**Comment by autonomousapps** [comment]
Published as 1.18.0 🎉

**Pull request merged**
