### PR TITLE
Generic types can be part of the ABI.

### PR DESCRIPTION
**Pull request by autonomousapps**
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/328.

### CODE REVIEW

**Comment by stephanenicolas** [comment]
Thx a lot @autonomousapps . I will act like if I understand every little bit and approve it. 
Though, I believe there is no code/test for annotations who have parameters that are classes. If the annotation is part of the api, so should be the type passed in parameter. Not sure it can be generics.

```
@FooAnnotation(BarParam.class)
public class FooClas { }
```

**Comment by autonomousapps** [comment]
Build failed https://gradle.com/s/l7uufqj5kniq4

**Comment by autonomousapps** [comment]
You are correct, I have no test for this yet and I suspect the plugin
would miss this case. Shouldn't be toooo hard to add this. Though I must

ask, what is up with these projects that use annotations scattered
across many separate dependencies :joy:

On November 24, 2020, GitHub <notifications@github.com> wrote:
> Thx a lot @autonomousapps <https://github.com/autonomousapps> . I will

> act like if I understand every little bit and approve it.
>  Though, I believe there is no code/test for annotations who have
> parameters that are classes. If the annotation is part of the api, so

> should be the type passed in parameter. Not sure it can be generics.

>
> @FooAnnotation(BarParam.class) public class FooClas { }

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-

plugin/pull/329#issuecomment-733446621>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5POGEKUMQ36QUPYOANTSRR5U5ANCNFSM4UBYXJCQ>.

**Comment by stephanenicolas** [comment]
I will give it a try soon. Thx @autonomousapps

**Comment by autonomousapps** [comment]
I hope to have this last (?!) case handled soon, as well. Might be in a

separate PR. 

On November 25, 2020, GitHub <notifications@github.com> wrote:
> I will give it a try soon. Thx @autonomousapps
> <https://github.com/autonomousapps>
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-

plugin/pull/329#issuecomment-734023307>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PONRVQA5PHTDIKC6FLSRWWLRANCNFSM4UBYXJCQ>.

**Comment by autonomousapps** [comment]
This PR https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/330 resolves the issue re
```kotlin
@Annotation(Foo::class)
```
`Foo` will now be recognized as part of the ABI.

**Pull request merged**
