### PR TITLE
Update supported version of AGP to 4.2.0-alpha16

### PR DESCRIPTION
**Pull request by stephanenicolas**

### CODE REVIEW

**Review by autonomousapps — COMMENTED** [review]
In `AbstractAndroidSpec`, please also update the test matrix by replacing this:
```kotlin
AgpVersion.version('4.2.0-alpha12')
```
with this:
```kotlin
AgpVersion.version('4.2.0-alpha16')
```

bonus points if you also update the changelog ;-)

**Comment by autonomousapps** [comment]
Ah, the earlier run failed because the latest alpha needs Gradle 6.7, and I'm currently testing against 6.1.1 and 6.6.1.

**Comment by autonomousapps** [comment]
Ok, that other PR has been merged. If you rebase and force-push, this should build (unless there are other issues).

**Comment by stephanenicolas** [comment]
Rebased :)
Glad I could help.

**Pull request merged**
